spring.application.name=journal_app
server.port=8082
spring.data.mongodb.auto-index-creation=true

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=test

# spring.data.mongodb.uri=mongodb+srv://rathodfalgun05_db_user:3BUrvrEe9ICIUofy@cluster0.cejjymd.mongodb.net/?appName=Cluster0retryWrites=true&w=majority

