# To activate a diffrent profile
# common configurations between all profiles are written here in default one.
spring:
  profiles:
    active: dev

server:
  port: 8083

# logging:
#   level:
#     com:
#       example:
#         journal_app: DEBUG

# logging:
#   level:
#     root: ERROR

