# To activate a diffrent profile
# common configurations between all profiles are written here in default one.
spring:
  profiles:
    active: default

server:
  port: 8083

Weather:
  apiKey: 3ae8d66b9e083e4dad4f6e89b5742ff3

# logging:
#   level:
#     com:
#       example:
#         journal_app: DEBUG

# logging:
#   level:
#     root: ERROR

